/**
 * ReviewRecord queries (spec: domain/domain-model.md "ReviewRecord").
 *
 * Append-only audit trail: a discriminated union on `kind` (daily /
 * weekly). There are deliberately NO update or soft-delete functions here —
 * the query layer never mutates or deletes a review record. The table is
 * declared as a regular upsert table (NOT createInsertOnly, so local writes
 * apply locally and stay readable offline); the append-only guarantee is
 * enforced at the server upload endpoint (database-guidelines.md "Upload
 * conflict policy v1").
 *
 * `snapshot` is machine-generated by a pure core function at review start;
 * `answers` are the user's checklist responses. Review decisions are
 * applied as real transactions — the record is the audit trail, the
 * entities are the state.
 */
import { assertReviewRecord, type ReviewRecord } from '@nextdo/core';
import { reviewRecordFromRow, reviewRecordToRow } from '../schema';
import type { NextdoDb } from '../types';

export async function listReviewRecords(
  db: NextdoDb,
  options?: { includeDeleted?: boolean },
): Promise<ReviewRecord[]> {
  let query = db.selectFrom('review_records').selectAll();
  if (!options?.includeDeleted) {
    query = query.where('deleted_at', 'is', null);
  }
  const rows = await query.orderBy('at').execute();
  return rows.map((row) => reviewRecordFromRow(row).record);
}

/**
 * Append a review record. core's hand-written pure validator
 * (`assertReviewRecord`) runs before the write — no zod or other runtime
 * dep in core (domain-model.md).
 */
export async function addReviewRecord(db: NextdoDb, record: ReviewRecord): Promise<ReviewRecord> {
  assertReviewRecord(record);
  await db
    .insertInto('review_records')
    .values({ id: record.id, ...reviewRecordToRow(record) })
    .execute();
  return record;
}
